prefijo = "http://semanticsearchiot.net/sswot/Ontologies#"
clase_event = "http://semanticsearchiot.net/sswot/Ontologies#Event"
clase_condition = "http://semanticsearchiot.net/sswot/Ontologies#Condition"
clase_Action = "http://semanticsearchiot.net/sswot/Ontologies#Action" 
clase_EntitiesOfInterert = "http://semanticsearchiot.net/sswot/Ontologies#EntitiesOfInterert"
clase_FeatureOfInterest = "http://purl.oclc.org/NET/ssnx/ssn#FeatureOfInterest"

 ##DataProperties: dp_ = "http://semanticsearchiot.net/sswot/Ontologies#"
dp_comparator_action = "http://semanticsearchiot.net/sswot/Ontologies#comparator_action"
dp_id_action_object = "http://semanticsearchiot.net/sswot/Ontologies#id_action_object"
dp_id_action_resource = "http://semanticsearchiot.net/sswot/Ontologies#id_action_resource"
dp_ip_action_object = "http://semanticsearchiot.net/sswot/Ontologies#ip_action_object"
dp_meaning_action = "http://semanticsearchiot.net/sswot/Ontologies#meaning_action"
dp_name_action_object = "http://semanticsearchiot.net/sswot/Ontologies#name_action_object"
dp_name_action_resource = "http://semanticsearchiot.net/sswot/Ontologies#name_action_resource"
dp_type_variable_action = "http://semanticsearchiot.net/sswot/Ontologies#type_variable_action"
dp_unit_action = "http://semanticsearchiot.net/sswot/Ontologies#unit_action"
dp_variable_action = "http://semanticsearchiot.net/sswot/Ontologies#variable_action"

dp_comparator_condition = "http://semanticsearchiot.net/sswot/Ontologies#comparator_condition"
dp_meaning_condition = "http://semanticsearchiot.net/sswot/Ontologies#meaning_condition"
dp_type_variable_condition = "http://semanticsearchiot.net/sswot/Ontologies#type_variable_condition"
dp_unit_condition = "http://semanticsearchiot.net/sswot/Ontologies#unit_condition"
dp_variable_condition = "http://semanticsearchiot.net/sswot/Ontologies#variable_condition"

dp_id_event_object = "http://semanticsearchiot.net/sswot/Ontologies#id_event_object"
dp_ip_event_object = "http://semanticsearchiot.net/sswot/Ontologies#ip_event_object"
dp_id_event_resource = "http://semanticsearchiot.net/sswot/Ontologies#id_event_resource"
dp_name_event_object = "http://semanticsearchiot.net/sswot/Ontologies#name_event_object"
dp_name_event_resource = "http://semanticsearchiot.net/sswot/Ontologies#name_event_resource"

dp_interest_entity_eca = "http://semanticsearchiot.net/sswot/Ontologies#interest_entity_eca"
dp_name_eca = "http://semanticsearchiot.net/sswot/Ontologies#name_eca"
dp_state_eca = "http://semanticsearchiot.net/sswot/Ontologies#state_eca"

dp_name_feature =  "http://semanticsearchiot.net/sswot/Ontologies#name_feature"
dp_name_entity = "http://semanticsearchiot.net/sswot/Ontologies#name_entity"

op_check = "http://semanticsearchiot.net/sswot/Ontologies#Check"
op_is_related_with = "http://semanticsearchiot.net/sswot/Ontologies#isRelatedWith"
op_starts_with = "http://semanticsearchiot.net/sswot/Ontologies#StartsWith"
