# Generated by Django 2.2.1 on 2019-06-15 15:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispositivos_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dispositivo_usuario',
            unique_together={('idUsuario', 'idDispositivo')},
        ),
    ]
