# Generated by Django 2.2.1 on 2019-06-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos_usuarios', '0002_auto_20190615_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dispositivo_usuario',
            unique_together=set(),
        ),
    ]
