# Generated by Django 2.2.2 on 2019-06-14 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo_Usuario',
            fields=[
                ('idDispositivo', models.IntegerField(primary_key=True, serialize=False)),
                ('idUsuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('idUsuario', 'idDispositivo')},
            },
        ),
    ]
