# Generated by Django 2.2.2 on 2019-06-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_dispositivo_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dispositivo_usuario',
            unique_together=set(),
        ),
    ]
