# Generated by Django 2.2.1 on 2019-06-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190614_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dispositivo_Usuario',
        ),
    ]
